import { FinancialGoal, Question, Card } from "../types/game";

export const BOARD_SIZE = 100;
export const BOARD_COLUMNS = 10;
export const BOARD_ROWS = 10;

export const FINANCIAL_GOALS: FinancialGoal[] = [
  { name: "Casa Propia", icon: "🏠", targetAmount: 100000 },
  { name: "Educación Avanzada", icon: "🎓", targetAmount: 80000 },
  { name: "Auto Familiar", icon: "🚗", targetAmount: 60000 },
  { name: "Viaje de Sueños", icon: "✈️", targetAmount: 50000 },
  { name: "Negocio Propio", icon: "💼", targetAmount: 120000 },
  { name: "Fondo de Salud", icon: "🏥", targetAmount: 40000 },
];

export const PLAYER_COLORS = [
  { name: "red", hex: "#e74c3c" },
  { name: "green", hex: "#2ecc71" },
  { name: "orange", hex: "#f39c12" },
  { name: "purple", hex: "#9b59b6" },
];

export const LADDERS: Record<number, number> = {
  2: 15,
  4: 21,
  10: 25,
  12: 23,
  25: 68,
  29: 79,
  42: 74,
  48: 87,
  51: 72,
  56: 77,
  62: 91,
  71: 91,
};

export const SNAKES: Record<number, number> = {
  27: 8,
  24: 7,
  18: 3,
  16: 6,
  36: 6,
  44: 22,
  47: 28,
  49: 11,
  55: 35,
  60: 20,
  64: 60,
  75: 31,
  78: 19,
  81: 38,
  88: 24,
  95: 56,
  99: 41,
};

export const OPPORTUNITIES: Card[] = [
  {
    type: "opportunity",
    title: "Inversión en Educación",
    icon: "🎓",
    description: "Completaste un curso especializado",
    amount: 8000,
  },
  {
    type: "opportunity",
    title: "Oportunidad de Inversión",
    icon: "📈",
    description: "Encontraste un negocio prometedor",
    amount: 12000,
  },
  {
    type: "opportunity",
    title: "Trabajo Extra",
    icon: "💼",
    description: "Conseguiste trabajo a medio tiempo",
    amount: 6000,
  },
  {
    type: "opportunity",
    title: "Alquiler de Propiedad",
    icon: "🏠",
    description: "Recibiste ingreso pasivo",
    amount: 5000,
  },
  {
    type: "opportunity",
    title: "Bono en el Trabajo",
    icon: "💰",
    description: "Recibiste un bono inesperado",
    amount: 10000,
  },
  {
    type: "opportunity",
    title: "Venta de Artículos",
    icon: "🛍️",
    description: "Vendiste cosas que no usabas",
    amount: 4500,
  },
  {
    type: "opportunity",
    title: "Premio en Lotería",
    icon: "🎁",
    description: "¡Ganaste un pequeño premio!",
    amount: 7000,
  },
  {
    type: "opportunity",
    title: "Freelance Completado",
    icon: "💻",
    description: "Terminaste un proyecto extra",
    amount: 9500,
  },
  {
    type: "opportunity",
    title: "Reembolso de Impuestos",
    icon: "📋",
    description: "Te devolvieron parte de los impuestos",
    amount: 6500,
  },
  {
    type: "opportunity",
    title: "Herencia Familiar",
    icon: "👨‍👩‍👧",
    description: "Recibiste una herencia",
    amount: 15000,
  },
];

export const CHALLENGES: Card[] = [
  {
    type: "challenge",
    title: "Reparación del Auto",
    icon: "🚗",
    description: "Mantenimiento urgente",
    amount: 8000,
  },
  {
    type: "challenge",
    title: "Emergencia Médica",
    icon: "🏥",
    description: "Gastos médicos inesperados",
    amount: 10000,
  },
  {
    type: "challenge",
    title: "Celular Dañado",
    icon: "📱",
    description: "Pantalla rota",
    amount: 4000,
  },
  {
    type: "challenge",
    title: "Subida de Servicios",
    icon: "💡",
    description: "Aumento en facturas",
    amount: 3000,
  },
  {
    type: "challenge",
    title: "Multa de Tránsito",
    icon: "🚔",
    description: "Infracción de tránsito",
    amount: 5000,
  },
  {
    type: "challenge",
    title: "Ropa Rota",
    icon: "👕",
    description: "Necesitas comprar ropa nueva",
    amount: 3500,
  },
  {
    type: "challenge",
    title: "Computadora con Virus",
    icon: "🦠",
    description: "Reparación de tecnología",
    amount: 6000,
  },
  {
    type: "challenge",
    title: "Accidente Doméstico",
    icon: "🏠",
    description: "Daños en la casa",
    amount: 7500,
  },
  {
    type: "challenge",
    title: "Deuda Antigua",
    icon: "💳",
    description: "Cobrador de deudas",
    amount: 9000,
  },
  {
    type: "challenge",
    title: "Pérdida de Dinero",
    icon: "😱",
    description: "Se te perdió dinero en la calle",
    amount: 2500,
  },
  {
    type: "challenge",
    title: "Entrada de Cine",
    icon: "🎬",
    description: "Gasto de entretenimiento",
    amount: 2000,
  },
  {
    type: "challenge",
    title: "Suscripción Olvidada",
    icon: "🔔",
    description: "Cobro que olvidaste cancelar",
    amount: 1500,
  },
];

export const QUESTIONS: Question[] = [
  {
    question: "María recibe $1.200.000 al mes y anota cuánto gasta en arriendo, comida y ahorro. ¿Qué está haciendo?",
    options: [
      "A. Presupuestar",
      "B. Pedir un préstamo",
      "C. Especular",
      "D. Evadir impuestos",
    ],
    correctAnswer: "A. Presupuestar",
    explanation: "Presupuestar es planificar y registrar ingresos y gastos",
    reward: 5000,
  },
  {
    question: "Jorge cobra $600.000 y automáticamente guarda $60.000 antes de gastar. ¿Cómo se llama esto?",
    options: [
      "A. Ahorro prioritario",
      "B. Gasto discrecional",
      "C. Crédito rotativo",
      "D. Donación",
    ],
    correctAnswer: "A. Ahorro prioritario",
    explanation: "El ahorro prioritario es apartar dinero antes de gastar",
    reward: 5000,
  },
  {
    question: "Sofía tiene $25.000: puede comprar leche (necesidad) o un refresco de marca (deseo). ¿Cuál es la necesidad?",
    options: [
      "A. Refresco de marca",
      "B. Leche",
      "C. Ninguno",
      "D. Ambos",
    ],
    correctAnswer: "B. Leche",
    explanation: "La leche es una necesidad básica, el refresco es un deseo",
    reward: 5000,
  },
  {
    question: "Un kilo de pan costaba $3.000 y ahora cuesta $3.900. ¿Qué fenómeno explica el aumento general de precios?",
    options: [
      "A. Deflación",
      "B. Inflación",
      "C. Depreciación del bien",
      "D. Subsidio",
    ],
    correctAnswer: "B. Inflación",
    explanation: "La inflación es el aumento generalizado de precios",
    reward: 5000,
  },
  {
    question: "Luis tenía un pequeño ahorro para emergencias y lo usó para reparar su lavadora sin pedir prestado. ¿Qué fondo utilizó?",
    options: [
      "A. Fondo de inversión",
      "B. Fondo de emergencia",
      "C. Cuenta corriente",
      "D. Préstamo informal",
    ],
    correctAnswer: "B. Fondo de emergencia",
    explanation: "El fondo de emergencia es dinero guardado para situaciones imprevistas",
    reward: 5000,
  },
  {
    question: "El banco presta $200.000 y pide devolver $220.000. Los $20.000 extra son:",
    options: [
      "A. Comisiones",
      "B. Intereses",
      "C. Multas",
      "D. Bonificación",
    ],
    correctAnswer: "B. Intereses",
    explanation: "Los intereses son el costo de pedir prestado dinero",
    reward: 5000,
  },
  {
    question: "Ana invierte $100.000; al mes gana intereses y luego intereses sobre esos intereses. ¿Cómo se llama esto?",
    options: [
      "A. Interés simple",
      "B. Interés compuesto",
      "C. Inflación",
      "D. Amortización",
    ],
    correctAnswer: "B. Interés compuesto",
    explanation: "El interés compuesto es cuando los intereses generan más intereses",
    reward: 5000,
  },
  {
    question: "Pedro decide salir con amigos en vez de estudiar para un examen importante. ¿Qué perdió por elegir salir?",
    options: [
      "A. El dinero del pasaje",
      "B. Tiempo de estudio",
      "C. La comida",
      "D. Nada",
    ],
    correctAnswer: "B. Tiempo de estudio",
    explanation: "El costo de oportunidad es lo que sacrificas al elegir una opción",
    reward: 5000,
  },
  {
    question: "Clara gana $900.000 y pide préstamos que la dejan pagando $1.200.000 mensuales. ¿Qué está pasando?",
    options: [
      "A. Buena administración",
      "B. Vivir por encima de las posibilidades",
      "C. Ahorro planificado",
      "D. Inversión agresiva",
    ],
    correctAnswer: "B. Vivir por encima de las posibilidades",
    explanation: "Gastar más de lo que se gana es vivir por encima de las posibilidades",
    reward: 5000,
  },
  {
    question: "Miguel instala una máquina de bebidas y gana dinero sin estar presente. ¿Qué tipo de ingreso recibe?",
    options: [
      "A. Ingreso laboral",
      "B. Ingreso pasivo",
      "C. Subsidio estatal",
      "D. Préstamo",
    ],
    correctAnswer: "B. Ingreso pasivo",
    explanation: "El ingreso pasivo es el dinero que ganas sin trabajar activamente",
    reward: 5000,
  },
  {
    question: "Sofía invierte en varias opciones distintas. ¿Qué está haciendo?",
    options: [
      "A. Concentrando riesgo",
      "B. Diversificando",
      "C. Especulando",
      "D. Ahorrando solo",
    ],
    correctAnswer: "B. Diversificando",
    explanation: "Diversificar es distribuir inversiones para reducir riesgo",
    reward: 5000,
  },
  {
    question: "Mario pide un crédito que puede pagar sin sacrificar sus necesidades básicas. ¿Qué práctica usa?",
    options: [
      "A. Sobreendeudamiento",
      "B. Endeudamiento responsable",
      "C. Fraude financiero",
      "D. Apuesta",
    ],
    correctAnswer: "B. Endeudamiento responsable",
    explanation: "El endeudamiento responsable es pedir prestado dentro de tus posibilidades",
    reward: 5000,
  },
  {
    question: "Carla compra una bicicleta para repartir domicilios y generar ingresos. ¿La bicicleta es?",
    options: [
      "A. Gasto corriente",
      "B. Activo",
      "C. Pasivo",
      "D. Deuda",
    ],
    correctAnswer: "B. Activo",
    explanation: "Un activo es algo que genera valor o ingresos",
    reward: 5000,
  },
  {
    question: "Tomás debe $700.000 por un televisor comprado a cuotas. Esa deuda es:",
    options: [
      "A. Activo",
      "B. Pasivo",
      "C. Inversión rentable",
      "D. Ingreso",
    ],
    correctAnswer: "B. Pasivo",
    explanation: "Un pasivo es una obligación o deuda que debes pagar",
    reward: 5000,
  },
  {
    question: "Una compra de $50.000 aparece con $9.500 adicionales por impuestos. Ese cargo extra es:",
    options: [
      "A. Subsidio",
      "B. Impuesto",
      "C. Comisión bancaria",
      "D. Propina",
    ],
    correctAnswer: "B. Impuesto",
    explanation: "Los impuestos son contribuciones obligatorias al gobierno",
    reward: 5000,
  },
  {
    question: "Natalia ahorra mensualmente durante 5 años para comprar vivienda. Esto es:",
    options: [
      "A. Ahorro a corto plazo",
      "B. Planificación a largo plazo",
      "C. Especulación",
      "D. Endiosamiento",
    ],
    correctAnswer: "B. Planificación a largo plazo",
    explanation: "La planificación a largo plazo es ahorrar para objetivos futuros",
    reward: 5000,
  },
  {
    question: "Solo hay 10 productos disponibles y 200 personas quieren comprarlos. ¿Qué pasa con el precio?",
    options: [
      "A. Baja el precio",
      "B. Sube el precio",
      "C. Se mantiene",
      "D. Se regala",
    ],
    correctAnswer: "B. Sube el precio",
    explanation: "Cuando la demanda supera la oferta, los precios suben",
    reward: 5000,
  },
  {
    question: "Compras hoy y pagas en dos meses con tu tarjeta. Esto es:",
    options: [
      "A. Ahorro programado",
      "B. Crédito",
      "C. Inversión directa",
      "D. Donación",
    ],
    correctAnswer: "B. Crédito",
    explanation: "El crédito permite comprar ahora y pagar después",
    reward: 5000,
  },
  {
    question: "Luis gana $2.500.000 y después de gastos le quedan $400.000. Ese dinero es:",
    options: [
      "A. Ingreso bruto",
      "B. Ingreso disponible",
      "C. Saldo negativo",
      "D. Deuda consolidada",
    ],
    correctAnswer: "B. Ingreso disponible",
    explanation: "El ingreso disponible es lo que queda después de los gastos",
    reward: 5000,
  },
  {
    question: "El empleador deposita automáticamente $20.000 al ahorro de Ana. Esto es:",
    options: [
      "A. Ahorro automático",
      "B. Retiro voluntario",
      "C. Cuenta corriente",
      "D. Crédito puente",
    ],
    correctAnswer: "A. Ahorro automático",
    explanation: "El ahorro automático es apartar dinero sin que tengas que hacerlo manualmente",
    reward: 5000,
  },
];

export const EVENT_SQUARES: Record<number, "opportunity" | "challenge" | "question"> = {
  3: "question",
  5: "opportunity",
  6: "challenge",
  8: "challenge",
  9: "opportunity",
  11: "challenge",
  13: "question",
  15: "opportunity",
  17: "challenge",
  19: "question",
  20: "challenge",
  22: "opportunity",
  24: "challenge",
  26: "question",
  28: "opportunity",
  30: "challenge",
  32: "question",
  34: "opportunity",
  35: "challenge",
  37: "question",
  39: "challenge",
  40: "opportunity",
  41: "challenge",
  43: "question",
  45: "opportunity",
  46: "challenge",
  50: "question",
  52: "opportunity",
  54: "challenge",
  57: "question",
  59: "opportunity",
  61: "challenge",
  63: "question",
  65: "opportunity",
  66: "challenge",
  69: "question",
  70: "opportunity",
  73: "challenge",
  76: "question",
  77: "opportunity",
  80: "challenge",
  82: "question",
  83: "opportunity",
  85: "challenge",
  86: "question",
  89: "opportunity",
  90: "challenge",
  91: "question",
  92: "opportunity",
  93: "challenge",
  94: "question",
  96: "opportunity",
  97: "challenge",
};

export const STARTING_MONEY = 0;
export const INITIAL_POSITION = 1;
